# Generated by Django 5.1.3 on 2024-11-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Слаг")),
                ("message_thread_id", models.IntegerField(verbose_name="ID топика")),
                ("message_template", models.TextField(verbose_name="Шаблон сообщения")),
            ],
            options={
                "verbose_name": "Форма",
                "verbose_name_plural": "Формы",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(verbose_name="Данные")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_sent", models.BooleanField(default=False, verbose_name="Отправлено")),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="informer.form",
                        verbose_name="Форма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
