# Generated by Django 5.1.3 on 2024-12-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="text",
            field=models.TextField(default="", verbose_name="Текст"),
            preserve_default=False,
        ),
    ]
