# Generated by Django 5.1.3 on 2024-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informer", "0002_form_name_message_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, default="", verbose_name="Текст"),
        ),
    ]
