# Generated by Django 5.1.3 on 2024-11-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
    ]
