# Generated by Django 5.1.3 on 2024-12-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_options_service_noindex_service_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Слаг")),
                ("order", models.IntegerField(blank=True, default=0, verbose_name="Порядковый номер")),
            ],
            options={
                "verbose_name": "Услуга: категория",
                "verbose_name_plural": "Услуга: категории",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.servicecategory",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
