# Generated by Django 5.1.3 on 2024-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_servicecategory_service_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricelistcategory",
            options={
                "ordering": ["order"],
                "verbose_name": "Прайс-лист: категория",
                "verbose_name_plural": "Прайс-лист: категории",
            },
        ),
        migrations.AlterModelOptions(
            name="pricelistitem",
            options={
                "ordering": ["order"],
                "verbose_name": "Прайс-лист: элемент категории",
                "verbose_name_plural": "Прайс-лист: элементы категорий",
            },
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "ordering": ["order"],
                "verbose_name": "Услуга: категория",
                "verbose_name_plural": "Услуга: категории",
            },
        ),
        migrations.AddField(
            model_name="pricelistcategory",
            name="order",
            field=models.IntegerField(blank=True, default=0, verbose_name="Порядковый номер"),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="order",
            field=models.IntegerField(blank=True, default=0, verbose_name="Порядковый номер"),
        ),
        migrations.AddField(
            model_name="service",
            name="show_in_slider",
            field=models.BooleanField(default=False, verbose_name="Показывать в слайдере"),
        ),
    ]
