# Generated by Django 5.1.3 on 2024-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_alter_pricelistcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="icon",
            field=models.ImageField(blank=True, upload_to="services", verbose_name="Иконка"),
        ),
    ]
