# Generated by Django 5.1.3 on 2024-12-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_servicecategory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="min_price",
            field=models.CharField(blank=True, max_length=255, verbose_name="Минимальная цена"),
        ),
    ]
