# Generated by Django 5.1.3 on 2024-12-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_service_min_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceStepBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("order", models.IntegerField(blank=True, default=0, verbose_name="Порядковый номер")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="services.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга: блок заказа",
                "verbose_name_plural": "Услуга: блок заказа",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceReasonBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("order", models.IntegerField(blank=True, default=0, verbose_name="Порядковый номер")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reasons",
                        to="services.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга: блок причин",
                "verbose_name_plural": "Услуга: блок причин",
                "ordering": ["order"],
            },
        ),
    ]
