# Generated by Django 5.1.3 on 2024-12-14 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_serviceorderblock_servicereasonblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Создан"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Создан"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="icon",
            field=models.FileField(blank=True, upload_to="services", verbose_name="Иконка"),
        ),
    ]
