# Generated by Django 5.1.3 on 2024-12-14 10:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_service_created_at_service_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="short_description",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="Текст (краткое описание)"),
        ),
        migrations.AddField(
            model_name="service",
            name="text",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="Текст"),
        ),
    ]
