# Generated by Django 5.1.3 on 2024-12-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_service_short_description_service_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicestepblock",
            options={
                "ordering": ["order"],
                "verbose_name": "Услуга: шаг оказания услуги",
                "verbose_name_plural": "Услуга: шаги оказания услуги",
            },
        ),
        migrations.AlterField(
            model_name="servicestepblock",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
    ]
