# Generated by Django 5.1.3 on 2025-01-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_remove_servicereasonblock_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price_list_categories",
            field=models.ManyToManyField(blank=True, related_name="services", to="services.pricelistcategory"),
        ),
    ]
