# Generated by Django 5.1.3 on 2025-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_service_price_list_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price_list_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="services",
                to="services.pricelistcategory",
                verbose_name="Категории прайс-листа",
            ),
        ),
    ]
