# Generated by Django 5.1.3 on 2025-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_alter_service_price_list_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, verbose_name="Активен"),
        ),
    ]
