# Generated by Django 5.1.3 on 2025-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0018_service_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="related_services",
            field=models.ManyToManyField(blank=True, to="services.service", verbose_name="Сопутствующие услуги"),
        ),
    ]
