# Generated by Django 5.1.3 on 2024-12-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("image", models.ImageField(upload_to="clients", verbose_name="Изображение")),
                ("order", models.IntegerField(blank=True, default=0, verbose_name="Порядковый номер")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["order"],
            },
        ),
    ]
