# Generated by Django 5.1.3 on 2024-11-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "html_upper",
                    models.TextField(blank=True, default="", verbose_name="Верхний блок HTML"),
                ),
                (
                    "html_bottom",
                    models.TextField(blank=True, default="", verbose_name="Нижний блок HTML"),
                ),
                (
                    "robots_txt",
                    models.TextField(blank=True, default="", verbose_name="robots.txt"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.site",
                        verbose_name="Сайт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки проекта",
                "verbose_name_plural": "Настройки проекта",
            },
        ),
    ]
