# Generated by Django 5.1.3 on 2024-11-25 13:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="email",
            field=models.CharField(default="", max_length=255, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="inn",
            field=models.CharField(default="", max_length=255, verbose_name="ИНН"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="kpp",
            field=models.CharField(default="", max_length=255, verbose_name="КПП"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="legal_address",
            field=models.CharField(default="", max_length=255, verbose_name="Юр.адрес"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="ogrn",
            field=models.CharField(default="", max_length=255, verbose_name="ОГРН"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="phone",
            field=models.CharField(default="", max_length=255, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="privacy_policy",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="Политика конфиденциальности"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="schedule",
            field=models.CharField(default="", max_length=255, verbose_name="График работы"),
        ),
    ]
