# Generated by Django 5.1.3 on 2024-12-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0003_projectsettings_ymaps_widget_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="phone_href",
            field=models.CharField(default="", max_length=255, verbose_name="Телефон для ссылок"),
        ),
    ]
