# Generated by Django 5.1.3 on 2024-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0004_projectsettings_phone_href"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(default="", max_length=255, verbose_name="Вопрос")),
                ("answer", models.CharField(default="", max_length=255, verbose_name="Ответ")),
                ("order", models.IntegerField(blank=True, default=0, verbose_name="Порядковый номер")),
            ],
            options={
                "verbose_name": "Часто задаваемый вопрос",
                "verbose_name_plural": "Часто задаваемые вопросы",
                "ordering": ["order"],
            },
        ),
    ]
