# Generated by Django 5.1.3 on 2024-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0005_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(default="", verbose_name="Ответ"),
        ),
    ]
