# Generated by Django 5.1.3 on 2024-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0006_alter_faq_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="ymaps_url",
            field=models.URLField(blank=True, default="", verbose_name="URL Яндекс.Карт"),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="ymaps_widget_url",
            field=models.URLField(blank=True, default="", verbose_name="URL виджета Яндекс.Карт"),
        ),
    ]
