# Generated by Django 5.1.3 on 2024-12-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0007_projectsettings_ymaps_url_and_more"),
        ("services", "0009_serviceorderblock_servicereasonblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faqs",
                to="services.service",
                verbose_name="Прикрепить к услуге",
            ),
        ),
    ]
