# Generated by Django 5.1.3 on 2024-12-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0008_faq_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="html_head",
            field=models.TextField(blank=True, default="", verbose_name="<head/> HTML"),
        ),
    ]
