# Generated by Django 5.1.3 on 2025-01-26 08:19

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0009_projectsettings_html_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("order", models.IntegerField(blank=True, default=0, verbose_name="Порядковый номер")),
                ("file", models.FileField(upload_to="contracts/files", verbose_name="Файл")),
                ("text", tinymce.models.HTMLField(blank=True, default="", verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Типовой договор",
                "verbose_name_plural": "Типовые договоры",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContractImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField(blank=True, default=0, verbose_name="Номер страницы")),
                ("image", models.ImageField(upload_to="contacts/images", verbose_name="Изображение")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="project_settings.contract",
                        verbose_name="Договор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Типовой договор: изображение",
                "verbose_name_plural": "Типовые договоры: изображения",
                "ordering": ["order"],
            },
        ),
    ]
