# Generated by Django 5.1.3 on 2025-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0010_contract_contractimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="telegram_link",
            field=models.CharField(default="", max_length=255, verbose_name="Telegram (ссылка)"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="whatsapp_link",
            field=models.CharField(default="", max_length=255, verbose_name="Whatsapp (ссылка)"),
        ),
    ]
