# Generated by Django 5.1.3 on 2025-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0011_projectsettings_telegram_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="whatsapp_link_number",
            field=models.CharField(
                default="", help_text="Без пробелов, плюса, скобок", max_length=255, verbose_name="Whatsapp (телефон)"
            ),
        ),
    ]
