# Generated by Django 5.1.3 on 2025-03-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0012_projectsettings_whatsapp_link_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="telegram_channel_link",
            field=models.CharField(default="", max_length=255, null=True, verbose_name="Telegram-канал (ссылка)"),
        ),
    ]
