# Generated by Django 5.1.3 on 2025-03-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_settings", "0013_projectsettings_telegram_channel_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="bitrix_source_id",
            field=models.URLField(blank=True, default="", verbose_name="Битрикс24 SOURCE ID"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="bitrix_user_id",
            field=models.URLField(blank=True, default="", verbose_name="Битрикс24 USER ID"),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="bitrix_webhook_url",
            field=models.URLField(blank=True, default="", verbose_name="Битрикс24 Webhook URL"),
        ),
    ]
