# Generated by Django 5.1.3 on 2024-12-18 18:11

from django.db import migrations, models

import core.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
                ("image", models.ImageField(upload_to="articles", verbose_name="Изображение")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Слаг")),
                ("date", models.DateField(verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-date"],
            },
            bases=(core.mixins.ImageModelMixin, models.Model),
        ),
    ]
