# Generated by Django 5.1.3 on 2024-12-21 11:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_articlecategory_article_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlecategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория статей",
                "verbose_name_plural": "Категории статей",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="text",
            field=tinymce.models.HTMLField(blank=True, default="", verbose_name="Текст"),
        ),
    ]
