# Generated by Django 5.1.3 on 2025-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_articlecategory_options_article_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="seo_description",
            field=models.TextField(blank=True, default="", verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_h1",
            field=models.TextField(blank=True, default="", verbose_name="SEO H1"),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_title",
            field=models.TextField(blank=True, default="", verbose_name="SEO Title"),
        ),
    ]
