# Generated by Django 5.1.3 on 2025-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_article_seo_description_article_seo_h1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, verbose_name="Активен"),
        ),
    ]
