# Generated by Django 5.1.3 on 2024-11-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Старый путь",
                    ),
                ),
                (
                    "new_path",
                    models.CharField(max_length=255, verbose_name="Новый путь"),
                ),
            ],
            options={
                "verbose_name": "Редирект",
                "verbose_name_plural": "Редиректы",
            },
        ),
        migrations.CreateModel(
            name="SeoParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Название"),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="/catalog/, /about/",
                        max_length=255,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "use_full_path",
                    models.BooleanField(default=False, verbose_name="Использовать полный путь"),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("h1", models.TextField(blank=True, null=True, verbose_name="H1")),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/background_image",
                        verbose_name="Фон шапки",
                    ),
                ),
                (
                    "fix_header",
                    models.BooleanField(default=True, verbose_name="Фиксировать шапку"),
                ),
                ("noindex", models.BooleanField(default=False, verbose_name="Noindex")),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/image",
                        verbose_name="og:image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр SEO",
                "verbose_name_plural": "Параметры SEO",
            },
        ),
    ]
